python 1_calculate_attribution.py \
    --model_name_or_path ../data/model/ep10_bert_large \
    --priv_data_path ../data/sampled_TEL.json \
    --output_dir ../Enorn_tel_bert_large_ep10_results/ \
    --output_prefix Enorn_tel_bert_large_ep10 \
    --gpus 4 \
    --max_seq_length 128 \
    --batch_size 20 \
    --num_batch 1 \
